/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ship_painter_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {14, 1, 1};

/* ship_painter_mpc_expl_vde_adj:(i0[10],i1[10],i2[4],i3[0])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a01=2.;
  a02=arg[2]? arg[2][0] : 0;
  a03=arg[1]? arg[1][7] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a05=(a00*a04);
  a06=arg[0]? arg[0][4] : 0;
  a07=arg[1]? arg[1][8] : 0;
  a08=(a02*a07);
  a08=(a01*a08);
  a09=(a06*a08);
  a05=(a05-a09);
  a09=arg[2]? arg[2][3] : 0;
  a10=5.0000000000000000e-01;
  a11=arg[1]? arg[1][6] : 0;
  a11=(a10*a11);
  a12=(a09*a11);
  a05=(a05+a12);
  a12=arg[2]? arg[2][2] : 0;
  a13=arg[1]? arg[1][5] : 0;
  a13=(a10*a13);
  a14=(a12*a13);
  a05=(a05+a14);
  a14=arg[2]? arg[2][1] : 0;
  a15=arg[1]? arg[1][4] : 0;
  a15=(a10*a15);
  a16=(a14*a15);
  a05=(a05+a16);
  if (res[0]!=0) res[0][3]=a05;
  a05=arg[0]? arg[0][6] : 0;
  a16=(a05*a04);
  a17=(a01*a06);
  a18=arg[1]? arg[1][9] : 0;
  a02=(a02*a18);
  a19=(a17*a02);
  a20=(a06*a02);
  a20=(a01*a20);
  a19=(a19+a20);
  a20=arg[0]? arg[0][3] : 0;
  a21=(a20*a08);
  a19=(a19+a21);
  a16=(a16-a19);
  a19=(a12*a11);
  a16=(a16+a19);
  a19=(a09*a13);
  a16=(a16-a19);
  a19=arg[1]? arg[1][3] : 0;
  a10=(a10*a19);
  a19=(a14*a10);
  a16=(a16-a19);
  if (res[0]!=0) res[0][4]=a16;
  a16=(a05*a08);
  a19=(a01*a00);
  a21=(a19*a02);
  a02=(a00*a02);
  a02=(a01*a02);
  a21=(a21+a02);
  a16=(a16-a21);
  a21=(a20*a04);
  a16=(a16+a21);
  a21=(a14*a11);
  a16=(a16-a21);
  a21=(a09*a15);
  a16=(a16+a21);
  a21=(a12*a10);
  a16=(a16-a21);
  if (res[0]!=0) res[0][5]=a16;
  a08=(a00*a08);
  a04=(a06*a04);
  a08=(a08+a04);
  a14=(a14*a13);
  a08=(a08+a14);
  a12=(a12*a15);
  a08=(a08-a12);
  a09=(a09*a10);
  a08=(a08-a09);
  if (res[0]!=0) res[0][6]=a08;
  a08=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][7]=a08;
  a08=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][8]=a08;
  a08=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][9]=a08;
  a08=1.;
  a17=(a17*a06);
  a08=(a08-a17);
  a19=(a19*a00);
  a08=(a08-a19);
  a08=(a08*a18);
  a18=(a00*a05);
  a19=(a20*a06);
  a18=(a18-a19);
  a18=(a01*a18);
  a18=(a18*a07);
  a08=(a08+a18);
  a18=(a20*a00);
  a07=(a06*a05);
  a18=(a18+a07);
  a01=(a01*a18);
  a01=(a01*a03);
  a08=(a08+a01);
  if (res[0]!=0) res[0][10]=a08;
  a08=(a05*a13);
  a01=(a00*a11);
  a08=(a08-a01);
  a01=(a20*a15);
  a08=(a08+a01);
  a01=(a06*a10);
  a08=(a08-a01);
  if (res[0]!=0) res[0][11]=a08;
  a08=(a06*a11);
  a01=(a20*a13);
  a08=(a08+a01);
  a01=(a05*a15);
  a08=(a08-a01);
  a01=(a00*a10);
  a08=(a08-a01);
  if (res[0]!=0) res[0][12]=a08;
  a20=(a20*a11);
  a06=(a06*a13);
  a20=(a20-a06);
  a00=(a00*a15);
  a20=(a20+a00);
  a05=(a05*a10);
  a20=(a20-a05);
  if (res[0]!=0) res[0][13]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_painter_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ship_painter_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_painter_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_painter_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ship_painter_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ship_painter_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ship_painter_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void ship_painter_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ship_painter_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ship_painter_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ship_painter_mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_painter_mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ship_painter_mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_painter_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ship_painter_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ship_painter_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ship_painter_mpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
